apiVersion: apps/v1
kind: Deployment
metadata:
  name: clacloteacherdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clacloteacher
  template:
    metadata:
      labels:
        app: clacloteacher
    spec:
      containers:
        - name: clacloteacher
          image: us-central1-docker.pkg.dev/comp7033-19274214/clacloteacher/teacher_claclo-api
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: MONGODB_USERNAME_19274214
              valueFrom:
                secretKeyRef:
                  name: mongodb-atlas-credentials
                  key: username
            - name: MONGODB_PASSWORD_COMP7033
              valueFrom:
                secretKeyRef:
                  name: mongodb-atlas-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: clacloteacher-service
spec:
  selector:
    app: clacloteacher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
